version: '3.7'

services:
  bulb-frontend:
    container_name: 'bulb-frontend-${APP_ENV}'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_ENV=${APP_ENV}
        - BACKEND_URL=${BACKEND_URL}
    ports:
      - ${APP_PORT}:${APP_PORT}
    expose:
      - ${APP_PORT}
    environment:
      - APP_PORT=${APP_PORT}
